version: '3'

services:

  mongodb:
    image: ghcr.io/zcube/bitnami-compat/mongodb:6.0
    container_name: mongodb
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=news
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - opensearch-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 1s
      timeout: 1s
      retries: 20
      start_period: 1s

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017/news?authSource=admin&directConnection=true
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    networks:
      - opensearch-network
    depends_on:
      mongodb:
        condition: service_healthy

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/news?authSource=admin&directConnection=true
    networks:
      - opensearch-network
    depends_on:
      mongodb:
        condition: service_healthy
      opensearch:
        condition: service_healthy

  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - plugins.ml_commons.only_run_on_ml_node=false
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  opensearch-init:
    image: curlimages/curl:latest
    container_name: opensearch-init
    volumes:
      - ./opensearch:/opensearch
    command: ["/opensearch/init.sh"]
    networks:
      - opensearch-network
    depends_on:
      opensearch:
        condition: service_healthy

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - opensearch-network
    depends_on:
      opensearch:
        condition: service_healthy

  monstache:
    image: rwynn/monstache:latest
    container_name: monstache
    volumes:
      - ./monstache/monstache-config.toml:/config.toml
    command: -f /config.toml
    networks:
      - opensearch-network
    depends_on:
      mongodb:
        condition: service_healthy
      opensearch:
        condition: service_healthy

networks:
  opensearch-network:
    driver: bridge

volumes:
  mongodb_data:
  opensearch-data: 
