# MongoDB connection string
mongo-url = "mongodb://mongodb:27017/news?authSource=admin&directConnection=true"

# OpenSearch connection
elasticsearch-urls = ["http://opensearch:9200"]

# Direct namespace mapping
direct-read-namespaces = ["news.posts", "news.pages", "news.users"]
direct-read-stateful = true

# Enable real-time sync
change-stream-namespaces = ["news.posts", "news.pages", "news.users"]

# Enable verbose logging for debugging
verbose = true

# Enable stats reporting
stats = true

# Enable resync on startup
resume = true

# Additional settings for better reliability
replay = true

config-database-name = "monstache-1"

[[mapping]]
namespace = "news.posts"
index = "posts-1"

[[mapping]]
namespace = "news.pages"
index = "pages-1"

[[mapping]]
namespace = "news.users"
index = "users-1"
