# MongoDB connection string
mongo-url = "mongodb://mongodb:27017/news?authSource=admin&directConnection=true"

# OpenSearch connection
elasticsearch-urls = ["http://opensearch:9200"]

# Direct namespace mapping
direct-read-namespaces = ["news.posts", "news.pages", "news.users"]

# Enable real-time sync
change-stream-namespaces = ["news.posts", "news.pages", "news.users"]

routing-namespaces = ["news.posts", "news.pages", "news.users"]

# Enable verbose logging for debugging
verbose = true

# Enable stats reporting
stats = true

# Enable resync on startup
resume = true

# Additional settings for better reliability
replay = true

config-database-name = "monstache-2"

[[mapping]]
namespace = "news.posts"
index = "branch-default"
pipeline = "posts-branch-ingest-pipeline"

[[mapping]]
namespace = "news.pages"
index = "branch-default"
pipeline = "pages-branch-ingest-pipeline"

[[mapping]]
namespace = "news.users"
index = "branch-default"
pipeline = "users-branch-ingest-pipeline"
